name: Build and Deploy to GCP

<<<<<<< HEAD
on:
  push:
    branches:
      - main
=======
steps:
  # Docker Build
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast3-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/myimage",
        ".",
        "--build-arg",
        "REACT_APP_MIPP_API_URL=${_REACT_APP_MIPP_API_URL}",
        "--build-arg",
        "REACT_APP_GOOGLE_CLIENT_ID=${_REACT_APP_GOOGLE_CLIENT_ID}",
      ]
    secretEnv: ["_REACT_APP_MIPP_API_URL", "_REACT_APP_GOOGLE_CLIENT_ID"]
>>>>>>> 342ba3cfa0f2acc71f574c730a91bb5351813d4d

jobs:
  deploy:
    runs-on: ubuntu-latest

<<<<<<< HEAD
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GCP Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/$GCP_PROJECT_ID/my-app:$GITHUB_SHA --build-arg REACT_APP_MIPP_API_URL=${{ secrets.REACT_APP_MIPP_API_URL }} --build-arg REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }} .
          gcloud auth configure-docker
          docker push gcr.io/$GCP_PROJECT_ID/my-app:$GITHUB_SHA

          - name: Deploy to Google Compute Engine
      run: |
        # 이미지 이름 설정
        IMAGE=gcr.io/$GCP_PROJECT_ID/my-app:$GITHUB_SHA

        # 인스턴스가 이미 존재하는지 확인
        if gcloud compute instances describe my-instance --zone asia-northeast3-c 2>/dev/null; then
          # 인스턴스 업데이트
          gcloud compute instances update-container my-instance --container-image $IMAGE --zone asia-northeast3-c
          # 새 인스턴스 생성
          gcloud compute instances create-with-container my-instance --container-image $IMAGE --zone asia-northeast3-c
        fi
=======
  # 기존 인스턴스 업데이트
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "compute",
        "instances",
        "update-container",
        "my-vm-name",
        "--container-image",
        "asia-northeast3-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/myimage",
      ]
    env: ["CLOUDSDK_COMPUTE_REGION=asia-northeast3", "CLOUDSDK_COMPUTE_ZONE=asia-northeast3-c"]

  # Deploy the container to a new VM instance
  # - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  #   entrypoint: "gcloud"
  #   timeout: 240s
  #   args:
  #     [
  #       "compute",
  #       "instances",
  #       "create-with-container",
  #       "my-vm-name",
  #       "--container-image",
  #       "asia-northeast3-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/myimage",
  #     ]
  #   env:
  #     - "CLOUDSDK_COMPUTE_REGION=asia-northeast3"
  #     - "CLOUDSDK_COMPUTE_ZONE=asia-northeast3-c"

availableSecrets:
  secretManager:
    - versionName: projects/486098542239/secrets/REACT_APP_MIPP_API_URL/versions/1
      env: "_REACT_APP_MIPP_API_URL"
    - versionName: projects/486098542239/secrets/REACT_APP_GOOGLE_CLIENT_ID/versions/1
      env: "_REACT_APP_GOOGLE_CLIENT_ID"
>>>>>>> 342ba3cfa0f2acc71f574c730a91bb5351813d4d
