options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
  # logsBucket: "gs://${_LOGS_BUCKET}"
  logging: "CLOUD_LOGGING_ONLY" # 또는 'NONE'

steps:
  # NPM Build with environment variables
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
    secretEnv: ["REACT_APP_MIPP_API_URL", "REACT_APP_GOOGLE_CLIENT_ID"]

  # Docker Build
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "asia-northeast3-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/myimage", "."]
    secretEnv: ["REACT_APP_MIPP_API_URL", "REACT_APP_GOOGLE_CLIENT_ID"]

  # Docker Push
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia-northeast3-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/myimage"]

  # Deploy the container to a new VM instance
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    timeout: 240s
    args:
      [
        "compute",
        "instances",
        "create-with-container",
        "my-vm-name",
        "--container-image",
        "asia-northeast3-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/myimage",
      ]
    env:
      - "CLOUDSDK_COMPUTE_REGION=asia-northeast3"
      - "CLOUDSDK_COMPUTE_ZONE=asia-northeast3-c"

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/REACT_APP_MIPP_API_URL/versions/latest
      env: "REACT_APP_MIPP_API_URL"
    - versionName: projects/${PROJECT_ID}/secrets/REACT_APP_GOOGLE_CLIENT_ID/versions/latest
      env: "REACT_APP_GOOGLE_CLIENT_ID"
