name: Deploy to Google Cloud Platform

on:
  push:
    branches:
      - main # main 브랜치에 push가 발생할 때 워크플로우를 트리거

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest # GitHub Actions 러너 설정

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # 현재 리포지토리를 체크아웃

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0 # Google Cloud SDK 설정
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }} # GCP 프로젝트 ID
          service_account_key: ${{ secrets.GCP_SA_KEY }} # 서비스 계정 키
          export_default_credentials: true

      - name: Install dependencies
        run: npm install # 의존성 설치

      - name: Build
        run: npm run build # 빌드 스크립트 실행

      - name: Deploy to Google Cloud
        run: | # Cloud Build를 사용하여 GCP에 배포
          gcloud builds submit --config cloudbuild.yaml .
