name: Build and Deploy to GCP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GCP Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{secrets.GCP_PROJECT_ID}}/my-app:$GITHUB_SHA --build-arg REACT_APP_MIPP_API_URL=${{ secrets.REACT_APP_MIPP_API_URL }} --build-arg REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }} .
          gcloud auth configure-docker
          docker push gcr.io/${{secrets.GCP_PROJECT_ID}}/my-app:$GITHUB_SHA

      - name: Deploy to Google Compute Engine
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:$GITHUB_SHA

          # 인스턴스가 이미 존재하는지 확인
          if gcloud compute instances describe my-instance --zone asia-northeast3-c 2>/dev/null; then
            # 인스턴스 업데이트
            gcloud compute instances update-container my-instance --container-image $IMAGE --zone asia-northeast3-c
          else
            # 새 인스턴스 생성
            gcloud compute instances create-with-container my-instance --container-image $IMAGE --zone asia-northeast3-c
          fi
          gcloud compute ssh slslslrhfem5@my-instance --zone asia-northeast3-c --command "\
            sudo docker run -p 80:3000 $IMAGE"
      # - name: Deploy to Compute Engine
      #   run: |
      #     # gcloud를 사용하여 Docker 컨테이너 실행 명령을 Compute Engine 인스턴스에 전송
      #     gcloud compute ssh slslslrhfem5@my-instance --zone asia-northeast3-c --command "\
      #       sudo docker stop my-app || true && \
      #       sudo docker rm my-app || true && \
      #       sudo docker run --name my-app -d -p 80:3000 gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:$GITHUB_SHA"

      # - name: Deploy React Build to GCP Instance via SSH
      #   run: |
      #     # SSH를 통해 GCP 인스턴스에 접근
      #     ssh -i ${{ secrets.SSH_PRIVATE_KEY }} username@your_instance_ip << 'EOF'
      #       # React 빌드 디렉토리로 이동
      #       cd /path/to/react/build
      #       # Apache 서버의 웹 루트 디렉토리로 빌드 결과물 복사
      #       sudo cp -r * /var/www/html
      #       # Apache 설정을 업데이트하고 서버 재시작
      #       sudo apache2ctl configtest
      #       sudo systemctl restart apache2
      #     EOF
      # 이 코드는 React 앱이 빌드된 후, SSH를 사용하여 GCP 인스턴스에 접근하고, React 앱의 빌드 결과물을 Apache의 웹 루트 디렉토리(/var/www/html)에 복사한 후, Apache 서버를 재시작하는 과정을 자동화합니다. username와 your_instance_ip는 각각 SSH 접근에 사용되는 GCP 인스턴스의 사용자 이름과 IP 주소로 대체해야 합니다. /path/to/react/build는 React 빌드 결과물이 위치한 디렉토리 경로로 대체해야 합니다.
