name: Build and Deploy to GCP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GCP Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/$GCP_PROJECT_ID/my-app:$GITHUB_SHA --build-arg REACT_APP_MIPP_API_URL=${{ secrets.REACT_APP_MIPP_API_URL }} --build-arg REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }} .
          gcloud auth configure-docker
          docker push gcr.io/$GCP_PROJECT_ID/my-app:$GITHUB_SHA

      - name: Deploy to Google Compute Engine
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:$GITHUB_SHA

          # 인스턴스가 이미 존재하는지 확인
          if gcloud compute instances describe my-instance --zone asia-northeast3-c 2>/dev/null; then
            # 인스턴스 업데이트
            gcloud compute instances update-container my-instance --container-image $IMAGE --zone asia-northeast3-c
            # 새 인스턴스 생성
            gcloud compute instances create-with-container my-instance --container-image $IMAGE --zone asia-northeast3-c
          fi
