name: Docker Build and Push to GCE

on:
  push:
    branches:
      - deploy

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: chosami/mipp-front:latest,
            chosami/mipp-front:v${{ github.run_number }}
          build-args: |
            REACT_APP_MIPP_API_URL=${{ secrets.REACT_APP_MIPP_API_URL }}
            REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
            PRERENDER_TOKEN=${{ secrets.PRERENDER_TOKEN }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Google Compute Engine
        run: |
          # 인스턴스에 SSH 접속하여 기존 Docker 컨테이너 정지 및 삭제
          gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME }} --zone asia-northeast3-a --command "\
          sudo docker stop $(sudo docker ps -aq) && \
          sudo docker rm $(sudo docker ps -aq) && \
          sudo docker rmi $(sudo docker images -q) --force || true"

          # 새 Docker 이미지 실행
          gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME }} --zone asia-northeast3-a --command "\
          sudo docker run -p 80:80 -d chosami/mipp-front:latest"
